"""
Русские названия часовых поясов, которыми AnimeGO подписывает время: «16:00 (Москва)», «(Хорватия)».

AnimeGO показывает время в поясе того IP, с которого пришёл запрос, а прокси ScraperAPI каждый раз разные.
Подпись — страна, если в ней один пояс, иначе город; плюс общие названия метазон CLDR.
За подписями из AMBIGUOUS_TIMEZONE_LABELS стоят пояса с разными смещениями — время с таких страниц не используется.

Файл сгенерирован scripts/generate_timezone_labels.py — не правьте руками:
новые подписи добавляйте в MANUAL_LABELS генератора и пересобирайте.
"""

TIMEZONE_LABELS = {
    'Абиджан': 'Africa/Abidjan',
    'Австрия': 'Europe/Vienna',
    'Адак': 'America/Adak',
    'Аддис-Абеба': 'Africa/Addis_Ababa',
    'Аделаида': 'Australia/Adelaide',
    'Аден': 'Asia/Aden',
    'Азербайджан': 'Asia/Baku',
    'Азорские о-ва': 'Atlantic/Azores',
    'Аккра': 'Africa/Accra',
    'Акри время': 'America/Eirunepe',
    'Актау': 'Asia/Aqtau',
    'Актобе': 'Asia/Aqtobe',
    'Аландские о-ва': 'Europe/Mariehamn',
    'Албания': 'Europe/Tirane',
    'Алжир': 'Africa/Algiers',
    'Алматы': 'Asia/Almaty',
    'Аляска': 'America/Anchorage',
    'Амазонка': 'America/Boa_Vista',
    'Американское Самоа': 'Pacific/Pago_Pago',
    'Амман': 'Asia/Amman',
    'Амстердам': 'Europe/Amsterdam',
    'Анадырь': 'Asia/Anadyr',
    'Ангилья': 'America/Anguilla',
    'Ангола': 'Africa/Luanda',
    'Андорра': 'Europe/Andorra',
    'Анкоридж': 'America/Anchorage',
    'Антананариву': 'Indian/Antananarivo',
    'Антигуа': 'America/Antigua',
    'Антигуа и Барбуда': 'America/Antigua',
    'Апиа': 'Pacific/Apia',
    'Арагуаина': 'America/Araguaina',
    'Аргентина': 'America/Argentina/Buenos_Aires',
    'Армения': 'Asia/Yerevan',
    'Аруба': 'America/Aruba',
    'Астрахань': 'Europe/Astrakhan',
    'Асунсьон': 'America/Asuncion',
    'Атырау': 'Asia/Atyrau',
    'Афганистан': 'Asia/Kabul',
    'Афины': 'Europe/Athens',
    'Ашхабад': 'Asia/Ashgabat',
    'Багамы': 'America/Nassau',
    'Багдад': 'Asia/Baghdad',
    'Баия': 'America/Bahia',
    'Баия-де-Бандерас': 'America/Bahia_Banderas',
    'Баку': 'Asia/Baku',
    'Бамако': 'Africa/Bamako',
    'Банги': 'Africa/Bangui',
    'Бангкок': 'Asia/Bangkok',
    'Бангладеш': 'Asia/Dhaka',
    'Банжул': 'Africa/Banjul',
    'Барбадос': 'America/Barbados',
    'Барнаул': 'Asia/Barnaul',
    'Бахрейн': 'Asia/Bahrain',
    'Бейрут': 'Asia/Beirut',
    'Беларусь': 'Europe/Minsk',
    'Белград': 'Europe/Belgrade',
    'Белен': 'America/Belem',
    'Белиз': 'America/Belize',
    'Бельгия': 'Europe/Brussels',
    'Бенин': 'Africa/Porto-Novo',
    'Берлин': 'Europe/Berlin',
    'Бермудские о-ва': 'Atlantic/Bermuda',
    'Бисау': 'Africa/Bissau',
    'Бишкек': 'Asia/Bishkek',
    'Бланк-Саблон': 'America/Blanc-Sablon',
    'Блантайр': 'Africa/Blantyre',
    'Боа-Виста': 'America/Boa_Vista',
    'Богота': 'America/Bogota',
    'Бойла, Северная Дакота': 'America/North_Dakota/Beulah',
    'Бойсе': 'America/Boise',
    'Болгария': 'Europe/Sofia',
    'Боливия': 'America/La_Paz',
    'Бонэйр, Синт-Эстатиус и Саба': 'America/Kralendijk',
    'Босния и Герцеговина': 'Europe/Sarajevo',
    'Ботсвана': 'Africa/Gaborone',
    'Браззавиль': 'Africa/Brazzaville',
    'Бразилия': 'America/Araguaina',
    'Братислава': 'Europe/Bratislava',
    'Брисбен': 'Australia/Brisbane',
    'Британская территория в Индийском океане': 'Indian/Chagos',
    'Брокен-Хилл': 'Australia/Broken_Hill',
    'Бруней': 'Asia/Brunei',
    'Брюссель': 'Europe/Brussels',
    'Бугенвиль': 'Pacific/Bougainville',
    'Будапешт': 'Europe/Budapest',
    'Бужумбура': 'Africa/Bujumbura',
    'Буркина-Фасо': 'Africa/Ouagadougou',
    'Бурунди': 'Africa/Bujumbura',
    'Бутан': 'Asia/Thimphu',
    'Бухарест': 'Europe/Bucharest',
    'Бюзинген-на-Верхнем-Рейне': 'Europe/Busingen',
    'Вадуц': 'Europe/Vaduz',
    'Ванкувер': 'America/Vancouver',
    'Вануату': 'Pacific/Efate',
    'Варшава': 'Europe/Warsaw',
    'Ватикан': 'Europe/Vatican',
    'Вевей, Индиана': 'America/Indiana/Vevay',
    'Великобритания': 'Europe/London',
    'Вена': 'Europe/Vienna',
    'Венгрия': 'Europe/Budapest',
    'Венесуэла': 'America/Caracas',
    'Вильнюс': 'Europe/Vilnius',
    'Виндхук': 'Africa/Windhoek',
    'Виннипег': 'America/Winnipeg',
    'Винсеннес': 'America/Indiana/Vincennes',
    'Виргинские о-ва (Великобритания)': 'America/Tortola',
    'Виргинские о-ва (США)': 'America/St_Thomas',
    'Владивосток': 'Asia/Vladivostok',
    'Волгоград': 'Europe/Volgograd',
    'Восток': 'Antarctica/Vostok',
    'Восточный Тимор': 'Asia/Dili',
    'Время в Самаре': 'Europe/Samara',
    'Время по Анадырю': 'Asia/Anadyr',
    'Вьентьян': 'Asia/Vientiane',
    'Вьетнам': 'Asia/Ho_Chi_Minh',
    'Габон': 'Africa/Libreville',
    'Габороне': 'Africa/Gaborone',
    'Гавана': 'America/Havana',
    'Газа': 'Asia/Gaza',
    'Гаити': 'America/Port-au-Prince',
    'Гайана': 'America/Guyana',
    'Галапагосские о-ва': 'Pacific/Galapagos',
    'Галифакс': 'America/Halifax',
    'Гамбия': 'Africa/Banjul',
    'Гана': 'Africa/Accra',
    'Гваделупа': 'America/Guadeloupe',
    'Гватемала': 'America/Guatemala',
    'Гвинея': 'Africa/Conakry',
    'Гвинея-Бисау': 'Africa/Bissau',
    'Германия': 'Europe/Berlin',
    'Гернси': 'Europe/Guernsey',
    'Гибралтар': 'Europe/Gibraltar',
    'Глейс-Бей': 'America/Glace_Bay',
    'Гондурас': 'America/Tegucigalpa',
    'Гонконг': 'Asia/Hong_Kong',
    'Гонконг (САР)': 'Asia/Hong_Kong',
    'Гонолулу': 'Pacific/Honolulu',
    'Гранд-Терк': 'America/Grand_Turk',
    'Гренада': 'America/Grenada',
    'Греция': 'Europe/Athens',
    'Грузия': 'Asia/Tbilisi',
    'Гуадалканал': 'Pacific/Guadalcanal',
    'Гуам': 'Pacific/Guam',
    'Гуаякиль': 'America/Guayaquil',
    'Гус-Бей': 'America/Goose_Bay',
    'Дакар': 'Africa/Dakar',
    'Дакка': 'Asia/Dhaka',
    'Дамаск': 'Asia/Damascus',
    'Дания': 'Europe/Copenhagen',
    'Дар-эс-Салам': 'Africa/Dar_es_Salaam',
    'Дарвин': 'Australia/Darwin',
    'Дейвис': 'Antarctica/Davis',
    'Денвер': 'America/Denver',
    'Денмарксхавн': 'America/Danmarkshavn',
    'Детройт': 'America/Detroit',
    'Джакарта': 'Asia/Jakarta',
    'Джаяпура': 'Asia/Jayapura',
    'Джерси': 'Europe/Jersey',
    'Джибути': 'Africa/Djibouti',
    'Джуба': 'Africa/Juba',
    'Джуно': 'America/Juneau',
    'Дили': 'Asia/Dili',
    'Доминика': 'America/Dominica',
    'Доминиканская Республика': 'America/Santo_Domingo',
    'Доусон': 'America/Dawson',
    'Доусон-Крик': 'America/Dawson_Creek',
    'Дуала': 'Africa/Douala',
    'Дубай': 'Asia/Dubai',
    'Дублин': 'Europe/Dublin',
    'Душанбе': 'Asia/Dushanbe',
    'Дюмон-д’Юрвиль': 'Antarctica/DumontDUrville',
    'Египет': 'Africa/Cairo',
    'Екатеринбург': 'Asia/Yekaterinburg',
    'Ереван': 'Asia/Yerevan',
    'Загреб': 'Europe/Zagreb',
    'Замбия': 'Africa/Lusaka',
    'Западная Австралия': 'Antarctica/Casey',
    'Западная Африка': 'Africa/Bangui',
    'Западная Европа': 'Atlantic/Canary',
    'Западная Сахара': 'Africa/El_Aaiun',
    'Зимбабве': 'Africa/Harare',
    'Иерусалим': 'Asia/Jerusalem',
    'Израиль': 'Asia/Jerusalem',
    'Икалуит': 'America/Iqaluit',
    'Индия': 'Asia/Kolkata',
    'Инувик': 'America/Inuvik',
    'Иордания': 'Asia/Amman',
    'Ирак': 'Asia/Baghdad',
    'Иран': 'Asia/Tehran',
    'Иркутск': 'Asia/Irkutsk',
    'Ирландия': 'Europe/Dublin',
    'Исландия': 'Atlantic/Reykjavik',
    'Испания': 'Europe/Madrid',
    'Италия': 'Europe/Rome',
    'Йемен': 'Asia/Aden',
    'Йоханнесбург': 'Africa/Johannesburg',
    'КНДР': 'Asia/Pyongyang',
    'Кабо-Верде': 'Atlantic/Cape_Verde',
    'Кабул': 'Asia/Kabul',
    'Казахстан': 'Asia/Almaty',
    'Каир': 'Africa/Cairo',
    'Кайенна': 'America/Cayenne',
    'Калининград': 'Europe/Kaliningrad',
    'Камбоджа': 'Asia/Phnom_Penh',
    'Камерун': 'Africa/Douala',
    'Кампала': 'Africa/Kampala',
    'Кампу-Гранди': 'America/Campo_Grande',
    'Канарские о-ва': 'Atlantic/Canary',
    'Канкун': 'America/Cancun',
    'Кантон': 'Pacific/Kanton',
    'Каракас': 'America/Caracas',
    'Карачи': 'Asia/Karachi',
    'Касабланка': 'Africa/Casablanca',
    'Катар': 'Asia/Qatar',
    'Кваджалейн': 'Pacific/Kwajalein',
    'Кеймбридж-Бей': 'America/Cambridge_Bay',
    'Кейси': 'Antarctica/Casey',
    'Кения': 'Africa/Nairobi',
    'Кергелен': 'Indian/Kerguelen',
    'Кигали': 'Africa/Kigali',
    'Киншаса': 'Africa/Kinshasa',
    'Кипр': 'Asia/Famagusta',
    'Киргизия': 'Asia/Bishkek',
    'Киритимати': 'Pacific/Kiritimati',
    'Киров': 'Europe/Kirov',
    'Китай': 'Asia/Shanghai',
    'Кишинев': 'Europe/Chisinau',
    'Кокосовые о-ва': 'Indian/Cocos',
    'Коломбо': 'Asia/Colombo',
    'Колумбия': 'America/Bogota',
    'Коморы': 'Indian/Comoro',
    'Конакри': 'Africa/Conakry',
    'Конго - Браззавиль': 'Africa/Brazzaville',
    'Копенгаген': 'Europe/Copenhagen',
    'Корея': 'Asia/Pyongyang',
    'Косрае': 'Pacific/Kosrae',
    'Коста-Рика': 'America/Costa_Rica',
    'Костанай': 'Asia/Qostanay',
    'Кот-д’Ивуар': 'Africa/Abidjan',
    'Кралендейк': 'America/Kralendijk',
    'Красноярск': 'Asia/Krasnoyarsk',
    'Крестон': 'America/Creston',
    'Куала-Лумпур': 'Asia/Kuala_Lumpur',
    'Куба': 'America/Havana',
    'Кувейт': 'Asia/Kuwait',
    'Кучинг': 'Asia/Kuching',
    'Куяба': 'America/Cuiaba',
    'Кызылорда': 'Asia/Qyzylorda',
    'Кюрасао': 'America/Curacao',
    'Ла-Пас': 'America/La_Paz',
    'Ла-Риоха': 'America/Argentina/La_Rioja',
    'Лагос': 'Africa/Lagos',
    'Лаос': 'Asia/Vientiane',
    'Латвия': 'Europe/Riga',
    'Лесото': 'Africa/Maseru',
    'Либерия': 'Africa/Monrovia',
    'Либревиль': 'Africa/Libreville',
    'Ливан': 'Asia/Beirut',
    'Ливия': 'Africa/Tripoli',
    'Лима': 'America/Lima',
    'Линдеман': 'Australia/Lindeman',
    'Лиссабон': 'Europe/Lisbon',
    'Литва': 'Europe/Vilnius',
    'Лихтенштейн': 'Europe/Vaduz',
    'Ломе': 'Africa/Lome',
    'Лонгйир': 'Arctic/Longyearbyen',
    'Лондон': 'Europe/London',
    'Лорд-Хау': 'Australia/Lord_Howe',
    'Лос-Анджелес': 'America/Los_Angeles',
    'Лоуэр-Принс-Куотер': 'America/Lower_Princes',
    'Луанда': 'Africa/Luanda',
    'Лубумбаши': 'Africa/Lubumbashi',
    'Лусака': 'Africa/Lusaka',
    'Любляна': 'Europe/Ljubljana',
    'Люксембург': 'Europe/Luxembourg',
    'Маврикий': 'Indian/Mauritius',
    'Мавритания': 'Africa/Nouakchott',
    'Магадан': 'Asia/Magadan',
    'Мадагаскар': 'Indian/Antananarivo',
    'Мадейра': 'Atlantic/Madeira',
    'Маджуро': 'Pacific/Majuro',
    'Мадрид': 'Europe/Madrid',
    'Майотта': 'Indian/Mayotte',
    'Мак-Мердо': 'Antarctica/McMurdo',
    'Макао': 'Asia/Macau',
    'Макао (САР)': 'Asia/Macau',
    'Макасар': 'Asia/Makassar',
    'Маккуори': 'Antarctica/Macquarie',
    'Малабо': 'Africa/Malabo',
    'Малави': 'Africa/Blantyre',
    'Малайзия': 'Asia/Kuala_Lumpur',
    'Мали': 'Africa/Bamako',
    'Мальдивы': 'Indian/Maldives',
    'Мальта': 'Europe/Malta',
    'Манагуа': 'America/Managua',
    'Манаус': 'America/Manaus',
    'Манила': 'Asia/Manila',
    'Мапуту': 'Africa/Maputo',
    'Маренго, Индиана': 'America/Indiana/Marengo',
    'Мариго': 'America/Marigot',
    'Мариехамн': 'Europe/Mariehamn',
    'Маркизские о-ва': 'Pacific/Marquesas',
    'Марокко': 'Africa/Casablanca',
    'Мартиника': 'America/Martinique',
    'Маршалловы о-ва': 'Pacific/Majuro',
    'Масатлан': 'America/Mazatlan',
    'Масейо': 'America/Maceio',
    'Масеру': 'Africa/Maseru',
    'Маскат': 'Asia/Muscat',
    'Матаморос': 'America/Matamoros',
    'Маэ': 'Indian/Mahe',
    'Мбабане': 'Africa/Mbabane',
    'Мельбурн': 'Australia/Melbourne',
    'Меномини': 'America/Menominee',
    'Мерида': 'America/Merida',
    'Метлакатла': 'America/Metlakatla',
    'Мехико': 'America/Mexico_City',
    'Микелон': 'America/Miquelon',
    'Минск': 'Europe/Minsk',
    'Могадишо': 'Africa/Mogadishu',
    'Мозамбик': 'Africa/Maputo',
    'Молдова': 'Europe/Chisinau',
    'Монако': 'Europe/Monaco',
    'Монктон': 'America/Moncton',
    'Монровия': 'Africa/Monrovia',
    'Монтевидео': 'America/Montevideo',
    'Монтеррей': 'America/Monterrey',
    'Монтиселло, Кентукки': 'America/Kentucky/Monticello',
    'Монтсеррат': 'America/Montserrat',
    'Москва': 'Europe/Moscow',
    'Моусон': 'Antarctica/Mawson',
    'Мьянма (Бирма)': 'Asia/Yangon',
    'Найроби': 'Africa/Nairobi',
    'Намибия': 'Africa/Windhoek',
    'Нассау': 'America/Nassau',
    'Науру': 'Pacific/Nauru',
    'Нджамена': 'Africa/Ndjamena',
    'Непал': 'Asia/Kathmandu',
    'Ниамей': 'Africa/Niamey',
    'Нигер': 'Africa/Niamey',
    'Нигерия': 'Africa/Lagos',
    'Нидерланды': 'Europe/Amsterdam',
    'Никарагуа': 'America/Managua',
    'Никосия': 'Asia/Nicosia',
    'Ниуэ': 'Pacific/Niue',
    'Новая Зеландия': 'Pacific/Auckland',
    'Новая Каледония': 'Pacific/Noumea',
    'Новокузнецк': 'Asia/Novokuznetsk',
    'Новосибирск': 'Asia/Novosibirsk',
    'Нокс, Индиана': 'America/Indiana/Knox',
    'Ном': 'America/Nome',
    'Норвегия': 'Europe/Oslo',
    'Норонья': 'America/Noronha',
    'Норфолк': 'Pacific/Norfolk',
    'Нуакшот': 'Africa/Nouakchott',
    'Нумеа': 'Pacific/Noumea',
    'Нью-Йорк': 'America/New_York',
    'Нью-Сейлем, Северная Дакота': 'America/North_Dakota/New_Salem',
    'Ньюфаундленд': 'America/St_Johns',
    'О-в Пасхи': 'Pacific/Easter',
    'ОАЭ': 'Asia/Dubai',
    'Окленд': 'Pacific/Auckland',
    'Оман': 'Asia/Muscat',
    'Омск': 'Asia/Omsk',
    'Осло': 'Europe/Oslo',
    'Острова Кайман': 'America/Cayman',
    'Острова Кука': 'Pacific/Rarotonga',
    'Охинага': 'America/Ojinaga',
    'Паго-Паго': 'Pacific/Pago_Pago',
    'Пакистан': 'Asia/Karachi',
    'Палау': 'Pacific/Palau',
    'Палестинские территории': 'Asia/Gaza',
    'Палмер': 'Antarctica/Palmer',
    'Панама': 'America/Panama',
    'Парагвай': 'America/Asuncion',
    'Парамарибо': 'America/Paramaribo',
    'Париж': 'Europe/Paris',
    'Перт': 'Australia/Perth',
    'Перу': 'America/Lima',
    'Петропавловск-Камчатский': 'Asia/Kamchatka',
    'Питерсберг, Индиана': 'America/Indiana/Petersburg',
    'Питкэрн': 'Pacific/Pitcairn',
    'Пномпень': 'Asia/Phnom_Penh',
    'Подгорица': 'Europe/Podgorica',
    'Польша': 'Europe/Warsaw',
    'Понтианак': 'Asia/Pontianak',
    'Порт-Морсби': 'Pacific/Port_Moresby',
    'Порт-о-Пренс': 'America/Port-au-Prince',
    'Порт-оф-Спейн': 'America/Port_of_Spain',
    'Порто-Ново': 'Africa/Porto-Novo',
    'Порту-Велью': 'America/Porto_Velho',
    'Португалия': 'Europe/Lisbon',
    'Прага': 'Europe/Prague',
    'Пунта-Аренас': 'America/Punta_Arenas',
    'Пуэрто-Рико': 'America/Puerto_Rico',
    'Пхеньян': 'Asia/Pyongyang',
    'Ранкин-Инлет': 'America/Rankin_Inlet',
    'Раротонга': 'Pacific/Rarotonga',
    'Реджайна': 'America/Regina',
    'Резольют': 'America/Resolute',
    'Рейкьявик': 'Atlantic/Reykjavik',
    'Ресифи': 'America/Recife',
    'Республика Корея': 'Asia/Seoul',
    'Реюньон': 'Indian/Reunion',
    'Рига': 'Europe/Riga',
    'Рим': 'Europe/Rome',
    'Рио-Гальегос': 'America/Argentina/Rio_Gallegos',
    'Риу-Бранку': 'America/Rio_Branco',
    'Ротера': 'Antarctica/Rothera',
    'Руанда': 'Africa/Kigali',
    'Румыния': 'Europe/Bucharest',
    'Сайпан': 'Pacific/Saipan',
    'Сальвадор': 'America/El_Salvador',
    'Сальта': 'America/Argentina/Salta',
    'Самара': 'Europe/Samara',
    'Самарканд': 'Asia/Samarkand',
    'Сан-Луис': 'America/Argentina/San_Luis',
    'Сан-Марино': 'Europe/San_Marino',
    'Сан-Паулу': 'America/Sao_Paulo',
    'Сан-Томе': 'Africa/Sao_Tome',
    'Сан-Томе и Принсипи': 'Africa/Sao_Tome',
    'Сан-Хуан': 'America/Argentina/San_Juan',
    'Сантарен': 'America/Santarem',
    'Санто-Доминго': 'America/Santo_Domingo',
    'Сантьяго': 'America/Santiago',
    'Сараево': 'Europe/Sarajevo',
    'Саратов': 'Europe/Saratov',
    'Саудовская Аравия': 'Asia/Aden',
    'Сахалин': 'Asia/Sakhalin',
    'Свифт-Керрент': 'America/Swift_Current',
    'Северная Македония': 'Europe/Skopje',
    'Северные Марианские о-ва': 'Pacific/Saipan',
    'Сейшельские о-ва': 'Indian/Mahe',
    'Сен-Бартелеми': 'America/St_Barthelemy',
    'Сен-Мартен': 'America/Marigot',
    'Сен-Пьер и Микелон': 'America/Miquelon',
    'Сенегал': 'Africa/Dakar',
    'Сент-Винсент': 'America/St_Vincent',
    'Сент-Винсент и Гренадины': 'America/St_Vincent',
    'Сент-Джонс': 'America/St_Johns',
    'Сент-Китс': 'America/St_Kitts',
    'Сент-Китс и Невис': 'America/St_Kitts',
    'Сент-Люсия': 'America/St_Lucia',
    'Сент-Томас': 'America/St_Thomas',
    'Сербия': 'Europe/Belgrade',
    'Сеул': 'Asia/Seoul',
    'Сеута': 'Africa/Ceuta',
    'Сидней': 'Australia/Sydney',
    'Симферополь': 'Europe/Simferopol',
    'Сингапур': 'Asia/Singapore',
    'Синт-Мартен': 'America/Lower_Princes',
    'Сирия': 'Asia/Damascus',
    'Ситка': 'America/Sitka',
    'Скопье': 'Europe/Skopje',
    'Скорсбисунн': 'America/Scoresbysund',
    'Словакия': 'Europe/Bratislava',
    'Словения': 'Europe/Ljubljana',
    'Соломоновы о-ва': 'Pacific/Guadalcanal',
    'Сомали': 'Africa/Mogadishu',
    'София': 'Europe/Sofia',
    'Среднеколымск': 'Asia/Srednekolymsk',
    'Стамбул': 'Europe/Istanbul',
    'Стокгольм': 'Europe/Stockholm',
    'Стэнли': 'Atlantic/Stanley',
    'Судан': 'Africa/Khartoum',
    'Суринам': 'America/Paramaribo',
    'Сьерра-Леоне': 'Africa/Freetown',
    'Сьюдад-Хуарес': 'America/Ciudad_Juarez',
    'Сёва': 'Antarctica/Syowa',
    'Таджикистан': 'Asia/Dushanbe',
    'Таиланд': 'Asia/Bangkok',
    'Таити': 'Pacific/Tahiti',
    'Тайбэй': 'Asia/Taipei',
    'Тайвань': 'Asia/Taipei',
    'Таллин': 'Europe/Tallinn',
    'Танзания': 'Africa/Dar_es_Salaam',
    'Тарава': 'Pacific/Tarawa',
    'Ташкент': 'Asia/Tashkent',
    'Тбилиси': 'Asia/Tbilisi',
    'Тегеран': 'Asia/Tehran',
    'Тегусигальпа': 'America/Tegucigalpa',
    'Телл-Сити': 'America/Indiana/Tell_City',
    'Тирана': 'Europe/Tirane',
    'Тихоокеанское мексиканское время': 'America/Hermosillo',
    'Тихуана': 'America/Tijuana',
    'Того': 'Africa/Lome',
    'Токелау': 'Pacific/Fakaofo',
    'Токио': 'Asia/Tokyo',
    'Томск': 'Asia/Tomsk',
    'Тонга': 'Pacific/Tongatapu',
    'Тонгатапу': 'Pacific/Tongatapu',
    'Торонто': 'America/Toronto',
    'Тортола': 'America/Tortola',
    'Тринидад и Тобаго': 'America/Port_of_Spain',
    'Триполи': 'Africa/Tripoli',
    'Тролль': 'Antarctica/Troll',
    'Тувалу': 'Pacific/Funafuti',
    'Тукуман': 'America/Argentina/Tucuman',
    'Туле': 'America/Thule',
    'Тунис': 'Africa/Tunis',
    'Туркменистан': 'Asia/Ashgabat',
    'Турция': 'Europe/Istanbul',
    'Тхимпху': 'Asia/Thimphu',
    'Тёркс и Кайкос': 'America/Grand_Turk',
    'Уагадугу': 'Africa/Ouagadougou',
    'Уайтхорс': 'America/Whitehorse',
    'Уганда': 'Africa/Kampala',
    'Узбекистан': 'Asia/Tashkent',
    'Уинамак': 'America/Indiana/Winamac',
    'Украина': 'Europe/Kyiv',
    'Улан-Батор': 'Asia/Ulaanbaatar',
    'Ульяновск': 'Europe/Ulyanovsk',
    'Уоллис': 'Pacific/Wallis',
    'Уоллис и Футуна': 'Pacific/Wallis',
    'Уральск': 'Asia/Oral',
    'Уругвай': 'America/Montevideo',
    'Урумчи': 'Asia/Urumqi',
    'Усть-Нера': 'Asia/Ust-Nera',
    'Ушуая': 'America/Argentina/Ushuaia',
    'Уэйк': 'Pacific/Wake',
    'Факаофо': 'Pacific/Fakaofo',
    'Фамагуста': 'Asia/Famagusta',
    'Фарерские о-ва': 'Atlantic/Faroe',
    'Фернанду-ди-Норонья': 'America/Noronha',
    'Фиджи': 'Pacific/Fiji',
    'Филиппины': 'Asia/Manila',
    'Финикс': 'America/Phoenix',
    'Финляндия': 'Europe/Helsinki',
    'Фолклендские о-ва': 'Atlantic/Stanley',
    'Форт Нельсон': 'America/Fort_Nelson',
    'Форталеза': 'America/Fortaleza',
    'Франция': 'Europe/Paris',
    'Французская Гвиана': 'America/Cayenne',
    'Французские Южные территории': 'Indian/Kerguelen',
    'Фритаун': 'Africa/Freetown',
    'Фунафути': 'Pacific/Funafuti',
    'Хандыга': 'Asia/Khandyga',
    'Хараре': 'Africa/Harare',
    'Хартум': 'Africa/Khartoum',
    'Хеврон': 'Asia/Hebron',
    'Хельсинки': 'Europe/Helsinki',
    'Хобарт': 'Australia/Hobart',
    'Ховд': 'Asia/Hovd',
    'Хорватия': 'Europe/Zagreb',
    'Центр, Северная Дакота': 'America/North_Dakota/Center',
    'Центральная Австралия, западное время': 'Australia/Eucla',
    'Центрально-Африканская Республика': 'Africa/Bangui',
    'Цюрих': 'Europe/Zurich',
    'Чагос': 'Indian/Chagos',
    'Чад': 'Africa/Ndjamena',
    'Чатем': 'Pacific/Chatham',
    'Черногория': 'Europe/Podgorica',
    'Чехия': 'Europe/Prague',
    'Чикаго': 'America/Chicago',
    'Чили': 'America/Santiago',
    'Чита': 'Asia/Chita',
    'Чиуауа': 'America/Chihuahua',
    'Шанхай': 'Asia/Shanghai',
    'Швейцария': 'Europe/Zurich',
    'Швеция': 'Europe/Stockholm',
    'Шпицберген и Ян-Майен': 'Arctic/Longyearbyen',
    'Шри-Ланка': 'Asia/Colombo',
    'Эдмонтон': 'America/Edmonton',
    'Эйрунепе': 'America/Eirunepe',
    'Эквадор': 'America/Guayaquil',
    'Экваториальная Гвинея': 'Africa/Malabo',
    'Эль-Аюн': 'Africa/El_Aaiun',
    'Эр-Рияд': 'Asia/Riyadh',
    'Эритрея': 'Africa/Asmara',
    'Эрмосильо': 'America/Hermosillo',
    'Эсватини': 'Africa/Mbabane',
    'Эстония': 'Europe/Tallinn',
    'Эфате': 'Pacific/Efate',
    'Эфиопия': 'Africa/Addis_Ababa',
    'Южная Георгия': 'Atlantic/South_Georgia',
    'Южная Георгия и Южные Сандвичевы о-ва': 'Atlantic/South_Georgia',
    'Южно-Африканская Республика': 'Africa/Johannesburg',
    'Южный Судан': 'Africa/Juba',
    'Юкла': 'Australia/Eucla',
    'Якутат': 'America/Yakutat',
    'Якутск': 'Asia/Yakutsk',
    'Ямайка': 'America/Jamaica',
    'Япония': 'Asia/Tokyo',
    'весь мир': 'Antarctica/Troll',
    'о-в Мэн': 'Europe/Isle_of_Man',
    'о-в Норфолк': 'Pacific/Norfolk',
    'о-в Пасхи': 'Pacific/Easter',
    'о-в Рождества': 'Indian/Christmas',
    'о-в Сахалин': 'Asia/Sakhalin',
    'о-в Св. Елены': 'Atlantic/St_Helena',
    'о-в Святой Елены': 'Atlantic/St_Helena',
    'о-ва Гамбье': 'Pacific/Gambier',
    'о-ва Кайман': 'America/Cayman',
    'о-ва Кука': 'Pacific/Rarotonga',
    'о-ва Мидуэй': 'Pacific/Midway',
    'о-ва Питкэрн': 'Pacific/Pitcairn',
}

# За этими подписями стоят пояса с разными смещениями — время с такой страницы не используется
AMBIGUOUS_TIMEZONE_LABELS = frozenset({
    'Атлантическое время',
    'Восточная Австралия',
    'Восточная Америка',
    'Восточная Европа',
    'Гавайско-алеутское время',
    'Горное время (Северная Америка)',
    'Самоа',
    'Тихоокеанское время',
    'Центральная Австралия',
    'Центральная Америка',
    'Центральная Европа',
})
