"""
Русские названия часовых поясов, которыми AnimeGO подписывает время: «16:00 (Москва)», «(Армения)».

AnimeGO показывает время в поясе того IP, с которого пришёл запрос, а прокси ScraperAPI каждый раз разные.
Названия — длинные общие имена CLDR (как babel.dates.get_timezone_name(zone, 'long', 'generic', locale='ru')).
Подписи, за которыми стоят пояса с разными смещениями (например, «Восточная Европа»: Калининград и Киев),
исключены — время с такой страницы не используется. Исключено: Атлантическое время, Восточная Австралия, Восточная Америка, Восточная Европа, Гавайско-алеутское время, Горное время (Северная Америка), Центральная Австралия, Центральная Америка, Центральная Европа.

Файл сгенерирован; пересобрать можно тем же вызовом babel по zoneinfo.available_timezones().
"""

TIMEZONE_LABELS = {
    'Азербайджан': 'Asia/Baku',
    'Азорские о-ва': 'Atlantic/Azores',
    'Акри время': 'America/Eirunepe',
    'Аляска': 'America/Anchorage',
    'Амазонка': 'America/Boa_Vista',
    'Антарктида (Восток), летнее время': 'Antarctica/Vostok',
    'Антарктида (Дейвис), летнее время': 'Antarctica/Davis',
    'Антарктида (Дюмон-д’Юрвиль), летнее время': 'Antarctica/DumontDUrville',
    'Антарктида (Моусон), летнее время': 'Antarctica/Mawson',
    'Антарктида (Палмер), летнее время': 'Antarctica/Palmer',
    'Антарктида (Ротера), летнее время': 'Antarctica/Rothera',
    'Антарктида (Сёва), летнее время': 'Antarctica/Syowa',
    'Апиа': 'Pacific/Apia',
    'Аргентина': 'America/Argentina/La_Rioja',
    'Аргентина (Argentina/Buenos Aires), летнее время': 'America/Argentina/Buenos_Aires',
    'Аргентина (Argentina/Catamarca), летнее время': 'America/Argentina/Catamarca',
    'Аргентина (Argentina/Cordoba), летнее время': 'America/Argentina/Cordoba',
    'Аргентина (Argentina/Jujuy), летнее время': 'America/Argentina/Jujuy',
    'Аргентина (Argentina/Mendoza), летнее время': 'America/Argentina/Mendoza',
    'Армения': 'Asia/Yerevan',
    'Афганистан, летнее время': 'Asia/Kabul',
    'Бангладеш': 'Asia/Dacca',
    'Боливия, летнее время': 'America/La_Paz',
    'Ботсвана, летнее время': 'Africa/Gaborone',
    'Бразилия': 'America/Araguaina',
    'Британская территория в Индийском океане, летнее время': 'Indian/Chagos',
    'Бруней, летнее время': 'Asia/Brunei',
    'Буркина-Фасо, летнее время': 'Africa/Ouagadougou',
    'Бурунди, летнее время': 'Africa/Bujumbura',
    'Бутан, летнее время': 'Asia/Thimbu',
    'Вануату': 'Pacific/Efate',
    'Великобритания, летнее время': 'Europe/Belfast',
    'Венесуэла, летнее время': 'America/Caracas',
    'Владивосток': 'Asia/Vladivostok',
    'Внешние малые о-ва (США) (Уэйк), летнее время': 'Pacific/Wake',
    'Волгоград': 'Europe/Volgograd',
    'Восточный Тимор, летнее время': 'Asia/Dili',
    'Время в Самаре': 'Europe/Samara',
    'Время по Анадырю': 'Asia/Anadyr',
    'Вьетнам, летнее время': 'Asia/Ho_Chi_Minh',
    'Гайана, летнее время': 'America/Guyana',
    'Гамбия, летнее время': 'Africa/Banjul',
    'Гана, летнее время': 'Africa/Accra',
    'Гвинея, летнее время': 'Africa/Conakry',
    'Гвинея-Бисау, летнее время': 'Africa/Bissau',
    'Гернси, летнее время': 'Europe/Guernsey',
    'Гонконг': 'Asia/Hong_Kong',
    'Гренландия (Nuuk), летнее время': 'America/Godthab',
    'Гренландия (Денмарксхавн), летнее время': 'America/Danmarkshavn',
    'Гренландия (Скорсбисунн), летнее время': 'America/Scoresbysund',
    'Грузия': 'Asia/Tbilisi',
    'Гуам, летнее время': 'Pacific/Guam',
    'Джерси, летнее время': 'Europe/Jersey',
    'Джибути, летнее время': 'Africa/Djibouti',
    'Екатеринбург': 'Asia/Yekaterinburg',
    'Замбия, летнее время': 'Africa/Lusaka',
    'Западная Австралия': 'Antarctica/Casey',
    'Западная Африка': 'Africa/Bangui',
    'Западная Европа': 'Atlantic/Canary',
    'Западная Сахара, летнее время': 'Africa/El_Aaiun',
    'Зимбабве, летнее время': 'Africa/Harare',
    'Израиль': 'Asia/Jerusalem',
    'Индия, летнее время': 'Asia/Calcutta',
    'Индонезия (Джакарта), летнее время': 'Asia/Jakarta',
    'Индонезия (Джаяпура), летнее время': 'Asia/Jayapura',
    'Индонезия (Макасар), летнее время': 'Asia/Makassar',
    'Индонезия (Понтианак), летнее время': 'Asia/Pontianak',
    'Иордания, летнее время': 'Asia/Amman',
    'Иран': 'Asia/Tehran',
    'Иркутск': 'Asia/Irkutsk',
    'Ирландия, летнее время': 'Europe/Dublin',
    'Исландия, летнее время': 'Atlantic/Reykjavik',
    'Кабо-Верде': 'Atlantic/Cape_Verde',
    'Казахстан (Актау), летнее время': 'Asia/Aqtau',
    'Казахстан (Актобе), летнее время': 'Asia/Aqtobe',
    'Казахстан (Алматы), летнее время': 'Asia/Almaty',
    'Казахстан (Атырау), летнее время': 'Asia/Atyrau',
    'Казахстан (Костанай), летнее время': 'Asia/Qostanay',
    'Казахстан (Кызылорда), летнее время': 'Asia/Qyzylorda',
    'Казахстан (Уральск), летнее время': 'Asia/Oral',
    'Камбоджа, летнее время': 'Asia/Phnom_Penh',
    'Канада (Atikokan), летнее время': 'America/Atikokan',
    'Канада (Доусон), летнее время': 'America/Dawson',
    'Канада (Уайтхорс), летнее время': 'America/Whitehorse',
    'Кения, летнее время': 'Africa/Nairobi',
    'Кипр (Фамагуста), летнее время': 'Asia/Famagusta',
    'Киргизия, летнее время': 'Asia/Bishkek',
    'Кирибати (Кантон), летнее время': 'Pacific/Enderbury',
    'Кирибати (Киритимати), летнее время': 'Pacific/Kiritimati',
    'Кирибати (Тарава), летнее время': 'Pacific/Tarawa',
    'Китай': 'Asia/Chongqing',
    'Китай (Урумчи), летнее время': 'Asia/Kashgar',
    'Кокосовые о-ва, летнее время': 'Indian/Cocos',
    'Колумбия': 'America/Bogota',
    'Коморы, летнее время': 'Indian/Comoro',
    'Конго - Киншаса (Лубумбаши), летнее время': 'Africa/Lubumbashi',
    'Корея': 'Asia/Seoul',
    'Кот-д’Ивуар, летнее время': 'Africa/Abidjan',
    'Красноярск': 'Asia/Krasnoyarsk',
    'Куба': 'America/Havana',
    'Лаос, летнее время': 'Asia/Vientiane',
    'Лесото, летнее время': 'Africa/Maseru',
    'Либерия, летнее время': 'Africa/Monrovia',
    'Лорд-Хау': 'Australia/LHI',
    'Маврикий': 'Indian/Mauritius',
    'Мавритания, летнее время': 'Africa/Nouakchott',
    'Магадан': 'Asia/Magadan',
    'Мадагаскар, летнее время': 'Indian/Antananarivo',
    'Майотта, летнее время': 'Indian/Mayotte',
    'Малави, летнее время': 'Africa/Blantyre',
    'Малайзия (Куала-Лумпур), летнее время': 'Asia/Kuala_Lumpur',
    'Малайзия (Кучинг), летнее время': 'Asia/Kuching',
    'Мали, летнее время': 'Africa/Bamako',
    'Мальдивы, летнее время': 'Indian/Maldives',
    'Марокко, летнее время': 'Africa/Casablanca',
    'Маршалловы о-ва (Кваджалейн), летнее время': 'Pacific/Kwajalein',
    'Маршалловы о-ва (Маджуро), летнее время': 'Pacific/Majuro',
    'Мозамбик, летнее время': 'Africa/Maputo',
    'Москва': 'Europe/Moscow',
    'Мьянма (Бирма), летнее время': 'Asia/Rangoon',
    'Намибия, летнее время': 'Africa/Windhoek',
    'Науру, летнее время': 'Pacific/Nauru',
    'Непал, летнее время': 'Asia/Kathmandu',
    'Ниуэ, летнее время': 'Pacific/Niue',
    'Новая Зеландия': 'Antarctica/South_Pole',
    'Новая Каледония': 'Pacific/Noumea',
    'Новосибирск': 'Asia/Novosibirsk',
    'Норфолк': 'Pacific/Norfolk',
    'Ньюфаундленд': 'America/St_Johns',
    'О-в Пасхи': 'Chile/EasterIsland',
    'ОАЭ, летнее время': 'Asia/Dubai',
    'Оман, летнее время': 'Asia/Muscat',
    'Омск': 'Asia/Omsk',
    'Острова Кука': 'Pacific/Rarotonga',
    'Пакистан': 'Asia/Karachi',
    'Палау, летнее время': 'Pacific/Palau',
    'Папуа — Новая Гвинея (Бугенвиль), летнее время': 'Pacific/Bougainville',
    'Папуа — Новая Гвинея (Порт-Морсби), летнее время': 'Pacific/Port_Moresby',
    'Парагвай': 'America/Asuncion',
    'Перу': 'America/Lima',
    'Петропавловск-Камчатский': 'Asia/Kamchatka',
    'Реюньон, летнее время': 'Indian/Reunion',
    'Россия (Астрахань), летнее время': 'Europe/Astrakhan',
    'Россия (Барнаул), летнее время': 'Asia/Barnaul',
    'Россия (Киров), летнее время': 'Europe/Kirov',
    'Россия (Саратов), летнее время': 'Europe/Saratov',
    'Россия (Среднеколымск), летнее время': 'Asia/Srednekolymsk',
    'Россия (Томск), летнее время': 'Asia/Tomsk',
    'Россия (Ульяновск), летнее время': 'Europe/Ulyanovsk',
    'Руанда, летнее время': 'Africa/Kigali',
    'Самоа': 'Pacific/Pago_Pago',
    'Сан-Томе и Принсипи, летнее время': 'Africa/Sao_Tome',
    'Саудовская Аравия': 'Asia/Riyadh',
    'Сахалин': 'Asia/Sakhalin',
    'Северные Марианские о-ва, летнее время': 'Pacific/Saipan',
    'Сейшельские о-ва, летнее время': 'Indian/Mahe',
    'Сен-Пьер и Микелон': 'America/Miquelon',
    'Сенегал, летнее время': 'Africa/Dakar',
    'Сингапур, летнее время': 'Asia/Singapore',
    'Сирия, летнее время': 'Asia/Damascus',
    'Соединенные Штаты (Indiana/Indianapolis), летнее время': 'America/Fort_Wayne',
    'Соединенные Штаты (Kentucky/Louisville), летнее время': 'America/Kentucky/Louisville',
    'Соломоновы о-ва, летнее время': 'Pacific/Guadalcanal',
    'Сомали, летнее время': 'Africa/Mogadishu',
    'Судан, летнее время': 'Africa/Khartoum',
    'Суринам, летнее время': 'America/Paramaribo',
    'Сьерра-Леоне, летнее время': 'Africa/Freetown',
    'Таджикистан, летнее время': 'Asia/Dushanbe',
    'Таиланд, летнее время': 'Asia/Bangkok',
    'Тайвань': 'Asia/Taipei',
    'Танзания, летнее время': 'Africa/Dar_es_Salaam',
    'Тихоокеанское время': 'America/Ensenada',
    'Тихоокеанское мексиканское время': 'America/Hermosillo',
    'Того, летнее время': 'Africa/Lome',
    'Токелау, летнее время': 'Pacific/Fakaofo',
    'Тонга': 'Pacific/Tongatapu',
    'Тувалу, летнее время': 'Pacific/Funafuti',
    'Туркменистан': 'Asia/Ashgabat',
    'Турция, летнее время': 'Asia/Istanbul',
    'Уганда, летнее время': 'Africa/Kampala',
    'Узбекистан': 'Asia/Samarkand',
    'Украина (Kyiv), летнее время': 'Europe/Kiev',
    'Улан-Батор': 'Asia/Choibalsan',
    'Уоллис и Футуна, летнее время': 'Pacific/Wallis',
    'Уругвай': 'America/Montevideo',
    'Фарерские о-ва, летнее время': 'Atlantic/Faeroe',
    'Федеративные Штаты Микронезии (Chuuk), летнее время': 'Pacific/Chuuk',
    'Федеративные Штаты Микронезии (Pohnpei), летнее время': 'Pacific/Pohnpei',
    'Федеративные Штаты Микронезии (Косрае), летнее время': 'Pacific/Kosrae',
    'Фернанду-ди-Норонья': 'America/Noronha',
    'Фиджи': 'Pacific/Fiji',
    'Филиппины': 'Asia/Manila',
    'Фолклендские о-ва': 'Atlantic/Stanley',
    'Французская Гвиана, летнее время': 'America/Cayenne',
    'Французская Полинезия (Маркизские о-ва), летнее время': 'Pacific/Marquesas',
    'Французская Полинезия (Таити), летнее время': 'Pacific/Tahiti',
    'Французская Полинезия (о-ва Гамбье), летнее время': 'Pacific/Gambier',
    'Французские Южные территории, летнее время': 'Indian/Kerguelen',
    'Ховд': 'Asia/Hovd',
    'Центральная Австралия, западное время': 'Australia/Eucla',
    'Чатем': 'Pacific/Chatham',
    'Чили': 'America/Santiago',
    'Чили (Пунта-Аренас), летнее время': 'America/Punta_Arenas',
    'Шри-Ланка, летнее время': 'Asia/Colombo',
    'Эквадор (Галапагосские о-ва), летнее время': 'Pacific/Galapagos',
    'Эквадор (Гуаякиль), летнее время': 'America/Guayaquil',
    'Эритрея, летнее время': 'Africa/Asmara',
    'Эсватини, летнее время': 'Africa/Mbabane',
    'Эфиопия, летнее время': 'Africa/Addis_Ababa',
    'Южная Георгия и Южные Сандвичевы о-ва, летнее время': 'Atlantic/South_Georgia',
    'Южно-Африканская Республика, летнее время': 'Africa/Johannesburg',
    'Южный Судан, летнее время': 'Africa/Juba',
    'Якутск': 'Asia/Yakutsk',
    'Япония': 'Asia/Tokyo',
    'весь мир (Тролль), летнее время': 'Antarctica/Troll',
    'неизвестный регион (Coyhaique), летнее время': 'America/Coyhaique',
    'о-в Мэн, летнее время': 'Europe/Isle_of_Man',
    'о-в Рождества, летнее время': 'Indian/Christmas',
    'о-в Св. Елены, летнее время': 'Atlantic/St_Helena',
    'о-ва Питкэрн, летнее время': 'Pacific/Pitcairn',
}
